### ISSUE TITLE
Made a new project in Rails 4.2.3; can't have icons 

### ISSUE THREAD

**Issue by bilalmaqsood** [nd0ut/semantic-ui-rails#26]
Just installed this gem in a newly created gem in a newly created Rails project using Rails 4.2.3, but can't have any icons there. Also, checked out the CSS and JS folder, there is no theme folder. Do I have to do something manually?

**Comment by nd0ut** [comment]
This gem is no longer maintained, sorry. Try to use https://github.com/doabit/semantic-ui-sass
